name: Build Ubuntu 22.04

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build-ubuntu:
    runs-on: ubuntu-22.04
      
    steps:
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt-get install ninja-build libprotobuf-dev libprotoc-dev protobuf-compiler

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules:  'true'
        fetch-depth: 0

    - name: CMake
      run: |
        export CC=/usr/bin/gcc-11
        export CXX=/usr/bin/g++-11
        mkdir "${{ runner.workspace }}/_build"
        cd "${{ runner.workspace }}/_build"
        cmake $GITHUB_WORKSPACE -G "Ninja" \
        -DBUILD_SAMPLES=ON \
        -DBUILD_SAMPLES_PROTOBUF=ON \
        -DBUILD_ECAL_TESTS=ON \
        -DBUILD_ECAL_TESTS_PROTOBUF=ON \
        -DECAL_CORE_REGISTRATION=ON \
        -DECAL_CORE_PUBLISHER=ON \
        -DECAL_CORE_SUBSCRIBER=ON \
        -DECAL_CORE_TRANSPORT_UDP=ON \
        -DECAL_CORE_TRANSPORT_TCP=ON \
        -DECAL_CORE_TRANSPORT_SHM=ON \
        -DECAL_CORE_TIMEPLUGIN=ON \
        -DECAL_CORE_NPCAP_SUPPORT=OFF \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_SYSCONFDIR=/etc \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LOCALSTATEDIR=/var \
        -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu
        sudo mkdir /etc/ecal
        sudo cp "$GITHUB_WORKSPACE/src/core/cfg/ecal.ini" /etc/ecal
      shell: bash

    - name: Build Release
      run: cmake --build . --config Release
      working-directory: ${{ runner.workspace }}/_build

    - name: Run Tests
      run: ctest -V
      working-directory: ${{ runner.workspace }}/_build
