name: Build macOS

on:  
  push:
  pull_request:
    branches:
      - main

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Install Dependencies
      run: brew install ninja protobuf pkg-config

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules:  'true'
        fetch-depth: 0

    - name: CMake
      run: |
        mkdir "${{ runner.workspace }}/_build"
        cd "${{ runner.workspace }}/_build"
        cmake $GITHUB_WORKSPACE -G "Ninja" \
        -DBUILD_SAMPLES=ON \
        -DBUILD_SAMPLES_PROTOBUF=ON \
        -DBUILD_ECAL_TESTS=ON \
        -DECAL_CORE_REGISTRATION=ON \
        -DECAL_CORE_PUBLISHER=ON \
        -DECAL_CORE_SUBSCRIBER=ON \
        -DECAL_CORE_TIMEPLUGIN=ON \
        -DECAL_CORE_NANOPB=ON \
        -DECAL_CORE_PROTOBUF=OFF \
        -DECAL_NPCAP_SUPPORT=OFF \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_CXX_STANDARD=17 \
        -DCMAKE_FIND_PACKAGE_PREFER_CONFIG=ON
        sudo mkdir /etc/ecal
        sudo cp "$GITHUB_WORKSPACE/src/core/cfg/ecal.ini" /etc/ecal
      shell: bash

    - name: Build Release
      run: cmake --build . --config Release
      working-directory: ${{ runner.workspace }}/_build

#    - name: Run Tests
#      run: ctest -V
#      working-directory: ${{ runner.workspace }}/_build
